<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.pisilinux.org/projeler/pisi/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>python3-backports_tarfile</Name>
        <Homepage>https://pypi.org/project/backports.tarfile/</Homepage>
        <Packager>
            <Name>PisiLinux Community</Name>
            <Email>admins@pisilinux.org</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app</IsA>
        <Summary>Backport of CPython tarfile module (from Python 3.12)</Summary>
        <Description>Backport of CPython tarfile module (from Python 3.12)</Description>
        <Archive sha1sum="3558f85d00164fadbd9d4112fddb4a5621782e65" type="targz">https://files.pythonhosted.org/packages/86/72/cd9b395f25e290e633655a100af28cb253e4393396264a98bd5f5951d50f/backports_tarfile-1.2.0.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>python3-devel</Dependency>
            <Dependency>python3-build</Dependency>
        </BuildDependencies>
        -->
        <!--
        <Patches>
            <Patch>python3-backports_tarfile.patch</Patch>
            <Patch level="1">python3-backports_tarfile.patch</Patch>
        </Patches>
        -->
    </Source>

    <Package>
        <Name>python3-backports_tarfile</Name>
        <RuntimeDependencies>
            <Dependency>python3</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="data">/usr/share</Path>
        </Files>
        <Conflicts>
            <Package>python3-backports-ssl-match-hostname</Package>
        </Conflicts>
    </Package>

    <History>
        <Update release="1">
            <Date>2025-04-18</Date>
            <Version>1.2.0</Version>
            <Comment>First release</Comment>
            <Name>PisiLinux Community</Name>
            <Email>admins@pisilinux.org</Email>
        </Update>
    </History>
</PISI>
